adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('home/', views.AdminHomeView.as_view(), name='admin_home'),
]

course_reg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('course/', include('courseapp.urls', namespace='courseapp')),
                  path('trainer/', include('trainers.urls', namespace='trainers')),
                  path('batch/', include('batchapp.urls', namespace='batchapp')),
                  path('student/', include('studentapp.urls',namespace='studentapp')),
                  path('admins/', include('adminapp.urls',namespace='adminapp')),
                  path('topic/', include('topicapp.urls', namespace='topicapp')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentapp/urls.py
from django.urls import path
from .views import student_register, course_view, each_course
from django.contrib.auth import views as auth_views
from userapp import views

app_name = 'studentapp'

urlpatterns = [
    path('', student_register, name='student_register'),
    path('view/', course_view, name='course_view'),
    path('<int:course_id>', each_course, name='each_course'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('main/', views.register_admin, name='register-admin'),
    path('student/', views.register_student, name='register-student'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.home, name='home'),  # Home URL for students
    path('home/', views.index_page, name='index_page'),  # Home URL for students
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact, name='contact'),
    path('view_students/', views.view_students, name='view_students'),
    path('<int:stud_id>', views.each_student_details, name='each_student_details'),
]

userapp/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True)
    phone = models.IntegerField(unique=True)
    message = models.TextField()

    def __str__(self):
        return self.name

userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class AdminRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class StudentRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)  # Add email as a required field

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

userapp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.forms import ModelForm
from .models import Contact
from studentapp.models import Student
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from .forms import AdminRegistrationForm, StudentRegistrationForm
from django.contrib.auth.models import Group
from django.contrib.auth import views as auth_views

# Create your views here.
class AdminDashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'admin-dashboard'

class StudentDashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'student-dashboard'

def register_admin(request):
    if request.method == 'POST':
        form = AdminRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Add the user to the 'Admin' group
            admin_group = Group.objects.get(name='Admin')
            user.groups.add(admin_group)
            login(request, user)  # Automatically log in the user
            return redirect('userapp:login')
    else:
        form = AdminRegistrationForm()
    
    return render(request, 'adminapp/register.html', {'form': form})

def register_student(request):
    if request.method == 'POST':
        form = StudentRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Add the user to the 'Student' group
            student_group = Group.objects.get(name='Student')
            user.groups.add(student_group)
            login(request, user)  # Automatically log in the user
            return redirect('userapp:login')
    else:
        form = StudentRegistrationForm()
    
    return render(request, 'userapp/register.html', {'form': form})

class CustomLoginView(auth_views.LoginView):
    template_name = 'userapp/login.html'

    def get_success_url(self):
        # Get the authenticated user
        user = self.request.user

        print(user.groups)

        # Check if the user is in the 'Admin' group
        if user.groups.filter(name='Admin').exists():
            return reverse('adminapp:admin_home')  # Redirect Admin users to admin dashboard

        # Check if the user is in the 'Student' group
        elif user.groups.filter(name='Student').exists():
            return reverse('userapp:home')  # Redirect Student users to student dashboard

        # Default fallback if no group match
        return reverse('userapp:home')  # Redirect to home or any default page

def home(request):
    return render(request, 'userapp/index.html')

# def admin_home(request):
#     return render(request, 'adminapp/home.html')

# index view
def index_page(request):
    return render(request, 'userapp/index.html')

# about view
def about_page(request):
    return render(request, 'userapp/about.html')


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


# contact view

def contact(request, template_name='userapp/contact.html'):
    contact_form = ContactForm(request.POST or None)
    if contact_form.is_valid():
        contact_form.save()
        return redirect('index_page')
    return render(request, template_name, {'contact_form': contact_form})


def view_students(request, template_name='userapp/students.html'):
    students_data = Student.objects.order_by('id')

    # students_search filter
    query = request.GET.get("q")
    if query:
        students_data = students_data.filter(
            Q(name__icontains=query) |
            Q(select_course__name__icontains=query) |
            Q(select_batch__batch_number__icontains=query)
        ).distinct()

    paginator = Paginator(students_data, 8)
    page = request.GET.get('page')
    students_page = paginator.get_page(page)

    context = {

        'students_data': students_page
    }
    return render(request, template_name, context)


# each students
def each_student_details(request, stud_id, template_name='userapp/each_stud_details.html'):
    stud = get_object_or_404(Student, pk=stud_id)
    context = {
        'stud': stud
    }
    return render(request, template_name, context)


#password reset
class CustomPasswordResetView(auth_views.PasswordResetView):
    # Custom template for rendering the password reset form
    template_name = 'userapp/password_reset_form.html'
    
    # Custom email template to be used for sending the password reset email
    email_template_name = 'userapp/password_reset_email.html'
    
    # URL to redirect after successful submission of password reset request
    success_url = reverse_lazy('userapp:password_reset_done')
    
    # Optional: Custom subject for the password reset email
    subject_template_name = 'userapp/password_reset_subject.txt'
    
    # Optional: Custom context for rendering the email
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_info'] = 'Some extra information'
        return context
    
# views.py
class CustomPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'userapp/password_reset_done.html'

# views.py
class CustomPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'userapp/password_reset_confirm.html'
    success_url = reverse_lazy('userapp:password_reset_complete')

# views.py
class CustomPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'userapp/password_reset_complete.html'

userapp/templates/userapp/about.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css" />
    <link rel="stylesheet" href="{% static 'style_new.css' %}">

  <title>About</title>
</head>

<body>
  <!-- navbar  -->
  {% include 'partial/_navbar2.html' %}
  <!-- page header -->
  {% include 'partial/_header.html'%}

  <!-- ABOUT SECTION -->
  <section id="about" class="py-3">
    <div class="container">
      <div class="row">
      </div>
    </div>
  </section>


<!--  &lt;!&ndash; TESTIMONIALS &ndash;&gt;-->
<!--  <section id="testimonials" class="p-4 text-white" style="background: #3b435b">-->
<!--    <div class="container">-->
<!--      <h2 class="text-center">Testimonials</h2>-->
<!--      <div class="row text-center">-->
<!--        <div class="col">-->
<!--          <div class="slider">-->
<!--            <div>-->
<!--              <blockquote class="blockquote">-->
<!--                <p class="mb-0">-->
<!--                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, quaerat.-->
<!--                </p>-->
<!--                <footer class="blockquote-footer">Akhil Paul-->
<!--                </footer>-->
<!--              </blockquote>-->
<!--            </div>-->
<!--            <div>-->
<!--              <blockquote class="blockquote">-->
<!--                <p class="mb-0">-->
<!--                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, quaerat.-->
<!--                </p>-->
<!--                <footer class="blockquote-footer">Joel Joy-->
<!--                </footer>-->
<!--              </blockquote>-->
<!--            </div>-->
<!--            <div>-->
<!--              <blockquote class="blockquote">-->
<!--                <p class="mb-0">-->
<!--                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, quaerat.-->
<!--                </p>-->
<!--                <footer class="blockquote-footer">Anu Abraham-->
<!--                </footer>-->
<!--              </blockquote>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </section>-->

<!--  footer -->
  <footer id="main-footer" class="text-center p-4 bg-dark text-light mt-4">
    <div class="container">
      <div class="row">
        <div class="col">
          <p>Copyright &copy;
            <span id="year">2024</span>&nbsp;
          </p>
        </div>
      </div>
    </div>
  </footer>





  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.js" integrity="sha256-zUQGihTEkA4nkrgfbbAM1f3pxvnWiznBND+TuJoUv3M=" crossorigin="anonymous"></script>

  <script>

    $('.slider').slick({
      infinite: true,
      slideToShow: 1,
      slideToScroll: 1
    });


  </script>
</body>

</html>

userapp/templates/userapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>My Python Trainer | User App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="My Python Trainer | Admin Panel" name="description" />
    <meta content="JC Web Technologies" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"
        id="bootstrap-stylesheet" />
    <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet" />
</head>

<body data-layout="horizontal">
    <div id="wrapper">
        <!--navbar-->
        {% include 'partial/_navbarhr.html' %}

        <!-- messages -->
        {% if messages %}
        <div class="container">
            <div class="row py-5">
                <div class="col-md-6">
                    {% for msg in messages %}
                    <!-- here v create an alert and grab the message tag for success -->
                    <div class="alert alert-{{msg.tags}}">
                        <!-- specify the message  -->
                        {{msg}}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="box-1" style="min-height: 80vh">
            {% block content%}
            {% endblock %}
        </div>

        {% include 'partial/_footer.html' %}

    </div>
    <script src="{% static 'assets/js/vendor.min.js' %}"></script>
    <script src="{% static 'assets/js/app.min.js' %}"></script>

</body>

</html>

userapp/templates/userapp/contact.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style_new.css' %}">
  <title>Contact</title>
</head>
<body>
<!--   navbar -->
 {% include 'partial/_navbar2.html' %}
<!--  page header -->

    <header id="page-header">
      <div class="container">
          <div class="row">
              <div class="col-md-6 text-center m-auto">
                  <h1>Contact Us</h1>
                  
              </div>
          </div>
      </div>
  </header>

<!-- contact form -->
    <section id="contact" class="py-5">
      <div class="container">
    
        <div class="row">
    
          <div class="col-md-8">
            <div class="card p-4">
              <div class="card-body">
                <h3 class="text-center">Please fill out this form to contact us</h3>
                <hr>
                <div class="row">
                  <div class="col-md-12">
                    <form method="POST">{% csrf_token %}
    
                      <div class="form-group">
                        {{contact_form|crispy}}
                      </div>
    
                      <!--      submit button -->
                      <div class="form-group">
                        <button type="submit" class="btn btn-outline-info btn-block">Submit</button>
                      </div>
    
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

<!--footer -->
 {% include  'partial/_footer.html' %}





</body>
</html>

userapp/templates/userapp/each_stud_details.html
{% extends 'userapp/base.html' %}

{% block content %}

<div class="container">
  <div class="row py-5">
    <div class="col-md-6">


      {% if stud %}

      <section id="bc" class="mb-5">

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'adminapp:admin_home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'userapp:view_students' %}">Students</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{stud.name}}</li>
          </ol>
        </nav>
      </section>


      <ul class="list-group list-group-flush">
        <li class="list-group-item text-secondary">First Name:
          <span class="float-right">{{stud.first_name}}</span>
        </li>

        <li class="list-group-item text-secondary">Last Name:
          <span class="float-right">{{stud.last_name}}</span>
        </li>

        <li class="list-group-item text-secondary">
          Email ID:
          <span class="float-right">{{stud.email_id}}</span>
        </li>

        <li class="list-group-item text-secondary">
          Mobile No:
          <span class="float-right">{{stud.phone_number}}</span>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

userapp/templates/userapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <title></title>
</head>
<style>
  </style>
<body>
    <!-- navbar -->
    {% include 'partial/_navbar2.html' %}

    <!-- page Header -->
    <header>
        <div id="showcase">
            <div class="showcase-content">
                <h1 class="display-4 text-center">
                  Student – Course Registration System
                </h1><hr><br>
                <div class="text-center">
                  <a href="{% url 'studentapp:course_view' %}" class="btn btn-outline-success">Explore</a>
                </div>
            </div><br><br>
        
        </div>
    </header>

    <!-- footer -->
    <footer id="main-footer" class="py-4 bg-dark text-white text-center">
            Copyright &copy;
            <span class="year">2024</span>
    </footer>




  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
    
</body>
</html>

userapp/templates/userapp/login.html
{% extends 'userapp/base.html' %}
<!--load crispy form-->
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3 mx-auto">
               <div class="card mt-3">
    <div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <!-- create a legend -->
            <legend class="border-bottom mb-4">

                Login
            </legend>
            {{form|crispy}}
        </fieldset>
        <!-- create a button -->
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info btn-block">Login</button>
        </div>
    </form>
    <!-- if already having account -->
    <div class="pt-2">
        <small class="text-muted">Forgot your password?
            <a href="{% url 'userapp:password_reset' %}" class="ml-3">Reset</a>
        </small>
        <br>
        <small class="text-muted">Need an Account?
            <a href="{% url 'userapp:register-student' %}" class="ml-3">Sign Up</a>
        </small>
    </div>
</div>
</div>
    </div>
    </div>
</div>
{% endblock %}

userapp/templates/userapp/logout.html
{% extends 'userapp/base.html' %}

{% block content %}
<div class="container">
    <div class="py-4">
        <p class="lead border-bottom">You Have been Logged out</p>
        <a href="{% url 'userapp:login' %}">Login Again</a>
    </div>
</div>
{% endblock %}

userapp/templates/userapp/no_access.html
<!-- templates/no_access.html -->
<h1>Access Denied</h1>
<p>You do not have permission to view this page.</p>

userapp/templates/userapp/password_reset_complete.html
{% extends 'userapp/base.html' %}

{% block title %}Password reset complete{% endblock %}

{% block content %}
<h1>Password reset complete</h1>
<p>Your password has been successfully reset. You can now <a href=" {% url 'userapp:login' %}">log in page</a>with your new password..</p>
{% endblock %}

userapp/templates/userapp/password_reset_confirm.html
{% extends "userapp/base.html" %}

{% block title %}Enter new password{% endblock %}

{% block content %}

{% if validlink %}

<h1>Set a new password!</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Reset Password</button>
</form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
</p>

{% endif %}
{% endblock %}

userapp/templates/userapp/password_reset_done.html
{% extends "userapp/base.html" %}

{% block title %}Email Sent{% endblock %}

{% block content %}
<h2>Password Reset Sent</h2>
<p>An email with a password reset link has been sent to the provided address.</p>
{% endblock %}

userapp/templates/userapp/password_reset_email.html
{% load i18n %}

{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{{ protocol }}://{{ domain }}{% url 'userapp:password_reset_confirm' uidb64=uid token=token %}

{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
{% endautoescape %}

userapp/templates/userapp/password_reset_form.html
{% extends 'userapp/base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
<h2>Reset your password</h2>
<p>Enter your email address, and we will send you a link to reset your password.</p>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Send Reset Link</button>
</form>
{% endblock %}

userapp/templates/userapp/register.html
{% extends 'userapp/base.html' %}
<!--load crispy form-->
{% load crispy_forms_tags %}

{% block content %}

<section id="register" class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <!-- create a legend -->
                                <h1 class="display-6 border-bottom">
                                    Register
                                </h1>
                                {{form|crispy}}
                            </div>
                            <!-- create a button -->
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-info btn-block">Sign Up</button>
                            </div>
                        </form>
                        <!-- if already having account -->
                        <div class="pt-2">
                            <small class="text-muted">Already Have an Account?
                                <a href="{% url 'userapp:login' %}" class="ml-3">Sign In</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}