adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('home/', views.AdminHomeView.as_view(), name='admin_home'),
]

batchapp/urls.py
from django.urls import path
from . import views

app_name = "batchapp"

urlpatterns = [
    path('', views.BatchFormView.as_view(), name='batch'),
    path('batches/', views.BatchListView.as_view(), name='batch_list'),
    path('<int:batch_id>', views.BatchDetailView.as_view(), name='each_batch'),
    path('delete/<int:pk>', views.BatchDelete.as_view(), name='batch_delete'),
    path('edit/<int:pk>', views.BatchEdit.as_view(), name='edit_batch'),
]

course_reg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('course/', include('courseapp.urls', namespace='courseapp')),
                  path('trainer/', include('trainers.urls', namespace='trainers')),
                  path('batch/', include('batchapp.urls', namespace='batchapp')),
                  path('student/', include('studentapp.urls',namespace='studentapp')),
                  path('admins/', include('adminapp.urls',namespace='adminapp')),
                  path('topic/', include('topicapp.urls', namespace='topicapp')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courseapp/urls.py
from django.urls import path
from . import views

app_name = "courseapp"

urlpatterns = [
    path('', views.CoursesFormView.as_view(), name='course_create'),
    path('course/', views.CourseListView.as_view(), name='course_list'),
    path('<int:pk>', views.CourseDetailView.as_view(), name='each_courses'),
    path('delete/<int:pk>', views.CourseDelete.as_view(), name='course_delete'),
    path('edit/<int:pk>', views.CourseEdit.as_view(), name='course_edit'),
]

topicapp/urls.py
from django.urls import path
from . import views

app_name = "topicapp"
urlpatterns = [
    path('', views.TopicFormView.as_view(), name='topic'),
    path('topics/', views.TopicListView.as_view(), name='topic_list'),
    path('<int:topic_id>', views.TopicDetailView.as_view(), name='each_topic'),
    path('delete/<int:pk>', views.TopicDelete.as_view(), name='topic_delete'),
    path('edit/<int:pk>', views.TopicEdit.as_view(), name='edit_topic'),
]

trainers/urls.py
from django.urls import path
from . import views

app_name = "trainers"
urlpatterns = [
    path('', views.TrainerFormView.as_view(), name='trainer_create'),
    path('trainers/', views.TrainersListView.as_view(), name='trainer_view'),
    path('<int:pk>', views.TrainerDetailView.as_view(), name='trainer_one'),
    path('delete/<int:pk>', views.TrainerDelete.as_view(), name='trainer_delete'),
    path('edit/<int:pk>', views.TrainerEdit.as_view(), name='trainer_edit'),
]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('main/', views.register_admin, name='register-admin'),
    path('student/', views.register_student, name='register-student'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.home, name='home'),  # Home URL for students
    path('home/', views.index_page, name='index_page'),  # Home URL for students
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact, name='contact'),
    path('view_students/', views.view_students, name='view_students'),
    path('<int:stud_id>', views.each_student_details, name='each_student_details'),
]

adminapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .adminforms import RegisterForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import TemplateView, FormView

# Create your views here.

class RegisterView(FormView):
    template_name = 'adminapp/register.html'  # Path to your template
    form_class = RegisterForm  # Your custom registration form
    success_url = reverse_lazy('userapp:login')  # Redirect after successful registration

    def form_valid(self, form):
        # Save the form to create the new user
        form.save()

        # Get the username from the form data
        username = form.cleaned_data.get('username')

        # Send a success message to the user
        messages.success(self.request, f'Account created for {username}!')

        # Call the superclass's form_valid method to handle the redirect
        return super().form_valid(form)
    
    def form_invalid(self, form):
        # You can add custom logic here if the form is invalid
        return super().form_invalid(form)


class AdminHomeView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'adminapp/home.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()

    # Handle unauthorized access (users who are not Admin)
    def handle_no_permission(self):
        return redirect('userapp:no-access')  # Redirect to a "no access" page or login page

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>My Python Trainer | Admin Panel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="My Python Trainer | Admin Panel" name="description" />
    <meta content="JC Web Technologies" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"
        id="bootstrap-stylesheet" />
    <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet" />
</head>

<body data-layout="horizontal">
    <div id="wrapper">
        <!--navbar-->
        {% include 'partial/_navbarhr.html' %}

        <!-- messages -->
        {% if messages %}
        <div class="contianer">
            <div class="row">

                <div class="col-md-6">
                    {% for msg in messages %}
                    <!-- here v create an alert and grab the message tag for success -->
                    <div class="alert alert-{{msg.tags}}">
                        <!-- specify the message  -->
                        {{msg}}
                    </div>
                    {% endfor %}

                </div>
                {% endif %}

            </div>
        </div>
        {% include 'partial/_footer.html' %}

    </div>
    <script src="{% static 'assets/js/vendor.min.js' %}"></script>
    <script src="{% static 'assets/js/app.min.js' %}"></script>

</body>

</html>

adminapp/templates/adminapp/home.html
{% extends 'adminapp/base.html' %}

{% block content %}

<div class="container">
     <div class="row py-5">
          <h1 class="text-info text-center">Admin Home</h1>

          <div class="col-md-12">

               <div class="dropdown show float-left mx-3">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Course</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                         <a class="dropdown-item" href="{% url 'courseapp:course_create' %}">Add</a>
                         <a class="dropdown-item" href="{% url 'courseapp:course_list' %}">View</a>
                    </div>
               </div>

               <div class="dropdown show float-left mx-3">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Batches</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                         <a class="dropdown-item" href="{% url 'batchapp:batch' %}">Add</a>
                         <a class="dropdown-item" href="{% url 'batchapp:batch_list' %}">View</a>
                    </div>
               </div>


               <div class="dropdown show float-left mx-3">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Students</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                         <a class="dropdown-item" href="{% url 'userapp:view_students' %}">View</a>
                    </div>
               </div>


               <div class="dropdown show float-left mx-3">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Trainers</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                         <a class="dropdown-item" href="{% url 'trainers:trainer_create' %}">Add</a>
                         <a class="dropdown-item" href="{% url 'trainers:trainer_view' %}">View</a>
                    </div>
               </div>

               <div class="dropdown show float-left mx-3">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Topics
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                         <a class="dropdown-item" href="{% url 'topicapp:topic' %}">Add</a>
                         <a class="dropdown-item" href="{% url 'topicapp:topic_list' %}">View</a>
                    </div>
               </div>


          </div>
     </div>
</div>
{% endblock %}

adminapp/templates/adminapp/register.html
{% extends 'adminapp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section id="register">
    <div class="container">
        <div class="row py-4">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <h2 class="text-secondary border-bottom">
                                    Admin Register
                                </h2>
                                {{form|crispy}}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-info btn-block">Register</button>
                            </div>
                        </form>
                        <div class="pt-2">
                            <small class="text-muted">Already have an Account?
                                <a href="{% url 'userapp:login' %}">Sign In</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}