adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('home/', views.AdminHomeView.as_view(), name='admin_home'),
]

course_reg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('course/', include('courseapp.urls', namespace='courseapp')),
                  path('trainer/', include('trainers.urls', namespace='trainers')),
                  path('batch/', include('batchapp.urls', namespace='batchapp')),
                  path('student/', include('studentapp.urls',namespace='studentapp')),
                  path('admins/', include('adminapp.urls',namespace='adminapp')),
                  path('topic/', include('topicapp.urls', namespace='topicapp')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainers/urls.py
from django.urls import path
from . import views

app_name = "trainers"
urlpatterns = [
    path('', views.TrainerFormView.as_view(), name='trainer_create'),
    path('trainers/', views.TrainersListView.as_view(), name='trainer_view'),
    path('<int:pk>', views.TrainerDetailView.as_view(), name='trainer_one'),
    path('delete/<int:pk>', views.TrainerDelete.as_view(), name='trainer_delete'),
    path('edit/<int:pk>', views.TrainerEdit.as_view(), name='trainer_edit'),
]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('main/', views.register_admin, name='register-admin'),
    path('student/', views.register_student, name='register-student'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.home, name='home'),  # Home URL for students
    path('home/', views.index_page, name='index_page'),  # Home URL for students
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact, name='contact'),
    path('view_students/', views.view_students, name='view_students'),
    path('<int:stud_id>', views.each_student_details, name='each_student_details'),
]

trainers/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator 
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from shared.constants import COUNTRY_CODES

def validate_gmail(email):
    if not email.endswith('@gmail.com'):
        raise ValidationError("Email must be a Gmail address.")
    if Trainer.objects.filter(email=email).exists():
        raise ValidationError("This email is already registered.")

# Create your models here.
class Trainer(models.Model):
    name = models.CharField(max_length=25)
    qualification = models.CharField(max_length=10)
    college = models.CharField(max_length=30)
    experience = models.PositiveIntegerField(validators=[MinValueValidator(3), MaxValueValidator(50)])
    training_exp = models.PositiveIntegerField(validators=[MinValueValidator(3), MaxValueValidator(50)])
    email = models.EmailField(max_length=60, validators=[validate_gmail])
    country_code = models.CharField(max_length=3, choices=COUNTRY_CODES, default='+91')
    
    phone_number = models.CharField(
        max_length=10,
        validators=[RegexValidator(r'^\d{10}$', 'Mobile number must be exactly 10 digits.')],
        help_text='Enter a valid 10-digit mobile number',
    )
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Trainer, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('trainer_one', kwargs={'pk': self.pk})

trainers/views.py
from django.shortcuts import get_object_or_404, redirect
from django.forms import ModelForm
from .models import Trainer
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, FormView, ListView, DetailView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

# create a model form
class TrainerForm(ModelForm):
    class Meta:
        model = Trainer
        fields = '__all__'
        exclude = ['status']


# Create your views here.
class TrainerFormView(LoginRequiredMixin, FormView):
    form_class = TrainerForm
    template_name = 'trainers/index.html' 
    success_url = reverse_lazy('trainers:trainer_view')

    def form_valid(self, form):
        trainer = form.save()
        trainer_name = trainer.name
        messages.success(self.request, f'Trainer with {trainer_name} created successfully')
        return super().form_valid(form)

# list trainers
class TrainersListView(ListView):
    model = Trainer
    context_object_name = 'data'
    template_name = 'trainers/trainers.html'
    ordering = ['-name']

    def post(self, request, *args, **kwargs):
        # Handle the status change when a checkbox is toggled
        trainer_id = request.POST.get('trainer_id')
        trainer = get_object_or_404(Trainer, id=trainer_id)
        trainer.status = not trainer.status  # Toggle the status
        trainer.save()

        # Redirect to the same page after the status is toggled
        return redirect('trainers:trainer_view') 
    
    def get_queryset(self):
        queryset = super().get_queryset().all().order_by('name')
        return queryset

# view each trainer details
class TrainerDetailView(LoginRequiredMixin, DetailView):
    model = Trainer
    template_name = 'trainers/each_trainer.html'
    context_object_name = 'new'

    def get_object(self):
        trainer_id = self.kwargs.get('pk')
        print(trainer_id)
        return get_object_or_404(Trainer, pk=trainer_id)

# remove trainer
class TrainerDelete(LoginRequiredMixin, DeleteView):
    model = Trainer
    success_url = reverse_lazy('trainer_view')

# edit a trainer
class TrainerEdit(LoginRequiredMixin, UpdateView):
    model = Trainer
    fields = ['name', 'qualification', 'college', 'experience', 'training_exp']
    success_url = reverse_lazy('trainer_view')

trainers/templates/trainers/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>My Python Trainer | Trainers App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="My Python Trainer | Admin Panel" name="description" />
    <meta content="JC Web Technologies" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"
        id="bootstrap-stylesheet" />
    <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet" />
</head>

<body data-layout="horizontal">
    <div id="wrapper">
        <!--navbar-->
        {% include 'partial/_navbarhr.html' %}

        <!-- messages -->
        {% if messages %}
        <div class="container">
            <div class="row py-5">
                <div class="col-md-6">
                    {% for msg in messages %}
                    <!-- here v create an alert and grab the message tag for success -->
                    <div class="alert alert-{{msg.tags}}">
                        <!-- specify the message  -->
                        {{msg}}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="box-1" style="min-height: 80vh">
            {% block content%}
            {% endblock %}
        </div>

        {% include 'partial/_footer.html' %}

    </div>
    <script src="{% static 'assets/js/vendor.min.js' %}"></script>
    <script src="{% static 'assets/js/app.min.js' %}"></script>

</body>

</html>

trainers/templates/trainers/each_trainer.html
{% extends 'trainers/base.html'%}


{% block content%}
<div class="container">
    <div class="row mb-5 fields mt-5">
    <div class="col-md-6">
    {% if new %}
        <!--breadcrumb -->
        <section id="bc" class="mb-5">
            <div class="container">

              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{% url 'adminapp:admin_home' %}">Home</a></li>
                  <li class="breadcrumb-item"><a href="{% url 'trainers:trainer_view' %}">Trainers</a></li>
                  <li class="breadcrumb-item active" aria-current="page">{{new.name}}</li>
                </ol>
              </nav>
            </div>
        </section>
    <ul class="list-group list-group-flush">
        <h1 class="text-info">Trainer Info</h1>
        <li class="list-group-item text-secondary">Name:
            <span class="float-right"> {{new.name}}</span>
        </li>
        <li class="list-group-item text-secondary">Email:
            <span class="float-right">{{new.email}}</span>
        </li>
        <li class="list-group-item text-secondary">Qualification:
            <span class="float-right">{{new.qualification}}</span>
        </li>
        <li class="list-group-item text-secondary">Experience:
            <span class="float-right">{{new.experience}}</span>
        </li>
        <li class="list-group-item text-secondary">Training Experience:
            <span class="float-right">{{new.training_exp}}</span>
        </li>
        <li class="list-group-item text-secondary">Mobile Number:
            <span class="float-right">{{new.country_code}} {{new.phone_number}}</span>
        </li>
        <li class="list-group-item text-secondary">Statuse:
            <span class="float-right">{{new.status}}</span>
        </li>

    </ul>
          <div class="pt-4">
        <a href="{% url 'trainers:trainer_edit' new.id %}" class="btn btn-secondary float-left px-4">Update</a>
        <a href="{% url 'trainers:trainer_delete' new.id %}" class="btn btn-danger float-right px-4">Delete</a>
            </div>
        {% endif %}
    </div>
    </div>
</div>





{% endblock%}

trainers/templates/trainers/index.html
{% extends 'trainers/base.html' %}

{% load crispy_forms_tags %}
{% load humanize %}

{% block content%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <br>
            <h1 class="text-info">Trainer Info</h1><br>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{form|crispy}}
                </fieldset>
                <div class="form-group">
                    <input class="btn btn-outline-info btn-block" type="submit" value="Save">
                    <a href="{% url 'trainers:trainer_create' %}" class="btn btn-outline-secondary btn-block">Cancel</a>
                </div>

            </form>
        </div>
    </div>
</div>


{% endblock %}

trainers/templates/trainers/trainer_confirm_delete.html
{% extends 'trainers/base.html' %}

{% block content%}
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-12">

    <form method="post">
        {% csrf_token %}
        <span class="text-center text-secondary">Are you sure want to delete "{{object.name}}" ?</span>

        <input type="submit" value="Submit" class="btn btn-secondary">
        <a href="{% url 'trainers:trainer_view' %}" class="btn btn-info ml-3">Back to Courses</a>
    </form>
            </div>
        </div>
    </div>
{% endblock %}

trainers/templates/trainers/trainer_form.html
{% extends 'trainers/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
    <div class="col-md-6">
        <form method="post">{% csrf_token %}
            <div class="form-group">
                {{form|crispy}}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-info btn-block">Save</button>
            </div>
        </form>
    </div>
    </div>
</div>


{% endblock %}

trainers/templates/trainers/trainers.html
{% extends 'trainers/base.html' %}

{% block content %}
<div class="container">
  <div class="row mb-5 mt-5">
    <div class="col-md-6">
      <!--        breadcrumb navigations -->
      <section id="bc" class="mb-5">
        <div class="container">

          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'adminapp:admin_home' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Trainers</li>
            </ol>
          </nav>
        </div>
      </section>


      {% if data %}


      <h1 class="text-info mt-3">
        Trainers
      </h1>

      <form method="post"></form>
      {% csrf_token %}
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Qualification</th>
            <th>College</th>
            <th>Experience</th>
            <th>Training Exp.</th>
            <th>Status (Active/Inactive)</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for trainer in data %}
          <tr>
            <td>
              <a class="list-group-item list-group-item-action" href="{% url 'trainers:trainer_one' trainer.pk %}">
                {{ trainer.name }}
              </a>
            </td>
            <td>{{ trainer.qualification }}</td>
            <td>{{ trainer.college }}</td>
            <td>{{ trainer.experience }}</td>
            <td>{{ trainer.training_exp }}</td>
            <td>
              <input type="checkbox" name="status" {% if trainer.status %} checked {% endif %} disabled>
            </td>
            <td>
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="trainer_id" value="{{ trainer.id }}">
                <button type="submit">
                  {% if trainer.status %} Deactivate {% else %} Activate {% endif %}
                </button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      </form>
      {% endif %}

    </div>
  </div>
</div>


{% endblock %}