adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('home/', views.AdminHomeView.as_view(), name='admin_home'),
]

batchapp/urls.py
from django.urls import path
from . import views

app_name = "batchapp"

urlpatterns = [
    path('', views.BatchFormView.as_view(), name='batch'),
    path('batches/', views.BatchListView.as_view(), name='batch_list'),
    path('<int:batch_id>', views.BatchDetailView.as_view(), name='each_batch'),
    path('delete/<int:pk>', views.BatchDelete.as_view(), name='batch_delete'),
    path('edit/<int:pk>', views.BatchEdit.as_view(), name='edit_batch'),
]

course_reg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('userapp.urls', namespace='userapp')),
                  path('course/', include('courseapp.urls', namespace='courseapp')),
                  path('trainer/', include('trainers.urls', namespace='trainers')),
                  path('batch/', include('batchapp.urls', namespace='batchapp')),
                  path('student/', include('studentapp.urls',namespace='studentapp')),
                  path('admins/', include('adminapp.urls',namespace='adminapp')),
                  path('topic/', include('topicapp.urls', namespace='topicapp')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topicapp/urls.py
from django.urls import path
from . import views

app_name = "topicapp"
urlpatterns = [
    path('', views.TopicFormView.as_view(), name='topic'),
    path('topics/', views.TopicListView.as_view(), name='topic_list'),
    path('<int:topic_id>', views.TopicDetailView.as_view(), name='each_topic'),
    path('delete/<int:pk>', views.TopicDelete.as_view(), name='topic_delete'),
    path('edit/<int:pk>', views.TopicEdit.as_view(), name='edit_topic'),
]

trainers/urls.py
from django.urls import path
from . import views

app_name = "trainers"
urlpatterns = [
    path('', views.TrainerFormView.as_view(), name='trainer_create'),
    path('trainers/', views.TrainersListView.as_view(), name='trainer_view'),
    path('<int:pk>', views.TrainerDetailView.as_view(), name='trainer_one'),
    path('delete/<int:pk>', views.TrainerDelete.as_view(), name='trainer_delete'),
    path('edit/<int:pk>', views.TrainerEdit.as_view(), name='trainer_edit'),
]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('main/', views.register_admin, name='register-admin'),
    path('student/', views.register_student, name='register-student'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.home, name='home'),  # Home URL for students
    path('home/', views.index_page, name='index_page'),  # Home URL for students
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact, name='contact'),
    path('view_students/', views.view_students, name='view_students'),
    path('<int:stud_id>', views.each_student_details, name='each_student_details'),
]

templates/partial/_footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                &copy; 2024 My Python Trainer | By <a href="https://jcwebtechnologies.com/?ref=mypt_footer">JCWT</a>
            </div>
        </div>
    </div>
</footer>

templates/partial/_header.html
  <header id="page-header">
      <div class="container">
          <div class="row">
              <div class="col-md-6 text-center m-auto">
                  <h1>About Us</h1>
                  <p>
                      
                  </p>
              </div>
          </div>
      </div>
  </header>

templates/partial/_navbar.html
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href="{% url 'userapp:index_page' %}" class="navbar-brand">Course Registration</a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'userapp:home' %}" class="nav-link">My Home
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'userapp:logout' %}" class="nav-link">
                    Logout
                </a></li>
            {% else %}
                       <li class="nav-item">
                <a href="{% url 'userapp:home' %}" class="nav-link d-none">My Home
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'userapp:logout' %}" class="nav-link d-none">
                    Logout
                </a></li>
                  <li class="nav-item">
                        <a href="{% url 'userapp:register-student' %}" class="nav-link">
                            Register
                        </a>
          </li>
              <li class="nav-item">
                    <a href="{% url 'userapp:login' %}" class="nav-link">
                        Login
                    </a>

          </li>
            {% endif %}




        </ul>
      </div>
    </div>
  </nav>

templates/partial/_navbar2.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href="{% url 'userapp:index_page' %}" class="navbar-brand">Course Registration</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">

      <ul class="navbar-nav ml-auto">
        <li {% if '/' == request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
          <a href="{% url 'userapp:index_page' %}" class="nav-link">Home</a>
        </li>
        <li {% if 'view' in request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
          <a href="{% url 'studentapp:course_view' %}" class="nav-link">Courses</a>
        </li>
        <li {% if 'about' in request.path %} class="nav-item active" {% else %} class=nav-item {% endif %}>
          <a href="{% url 'userapp:about_page' %}" class="nav-link">About Us</a>
        </li>
        <li {% if 'contact' in request.path%} class="nav-item active" {% else %} class="nav-item" {% endif %}>
          <a href="{% url 'userapp:contact' %}" class="nav-link">Contact</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'userapp:logout' %}" class="nav-link">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'userapp:login' %}" class="nav-link">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>

</nav>

templates/partial/_navbarhr.html
{% load static %}
<header id="topnav">
  <!-- Topbar Start -->
  <div class="navbar-custom">
      <div class="container-fluid">
          <ul class="list-unstyled topnav-menu float-right mb-0">

              <li class="dropdown notification-list">
                  <!-- Mobile menu toggle-->
                  <a class="navbar-toggle nav-link">
                      <div class="lines">
                          <span></span>
                          <span></span>
                          <span></span>
                      </div>
                  </a>
                  <!-- End mobile menu toggle-->
              </li>

              <li class="dropdown notification-list">
                  <a class="nav-link dropdown-toggle nav-user mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                      <img src="{% static 'assets/images/users/profile-user.jpg' %}" alt="user-image" class="rounded-circle">
                      <span class="pro-user-name d-none d-xl-inline-block ml-2">Admin<i class="mdi mdi-chevron-down"></i> 
                                      </span>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                      <div class="dropdown-header noti-title">
                          <h6 class="text-overflow m-0">Welcome!</h6>
                      </div>
                      <a href="javascript:void(0);" class="dropdown-item notify-item">
                          <i class="mdi mdi-account-outline"></i>
                          <span>Profile</span>
                      </a>
                      <div class="dropdown-divider"></div>
                      <a href="javascript:void(0);" class="dropdown-item notify-item">
                          <i class="mdi mdi-logout-variant"></i>
                          <span>Logout</span>
                      </a>
                  </div>
              </li>

          </ul>

          <!-- LOGO -->
          <div class="logo-box">
              <a href="{% url 'adminapp:admin_home' %}" class="logo text-center">
                  <span class="logo-lg">
                          <!--<img src="assets/images/logo-light.png" alt="" height="26">-->
                          <span class="logo-lg-text-light">My Python Trainer</span>
                  </span>
                  <span class="logo-sm">
      <img src="{% static 'assets/images/logo-sm.png' %}" alt="" height="22">
                          <!-- <span class="logo-sm-text-dark">Python Trainer Admin</span> -->
                  </span>
              </a>
          </div>

          <div id="navigation">
              <!-- Navigation Menu-->
              <ul class="navigation-menu">

                  <li>
                      <a href="{% url 'adminapp:admin_home' %}">
                          <i class="ti-home"></i>Home
                      </a>
                  </li>

                  <li class="has-submenu">
                      <a href="#"> <i class="ti-user"></i>Batches</a>
                      <ul class="submenu">
                          <li><a href="{% url 'batchapp:batch' %}">Add New Batch</a></li>
                          <li><a href="{% url 'batchapp:batch_list' %}">View All Batches</a></li>

                      </ul>
                  </li>
  
  <li class="has-submenu">
                      <a href="#"> <i class="ti-book"></i>Courses</a>
                      <ul class="submenu">
                          <li><a href="{% url 'courseapp:course_create' %}">Add New Course</a></li>
                          <li><a href="{% url 'courseapp:course_list' %}">View All Courses</a></li>

                      </ul>
                  </li>
  
  <li class="has-submenu">
                      <a href="#"> <i class="ti-bookmark"></i>Topics</a>
                      <ul class="submenu">
                          <li><a href="{% url 'topicapp:topic' %}">Add New Topic</a></li>
                          <li><a href="{% url 'topicapp:topic_list' %}">View All Topics</a></li>

                      </ul>
                  </li>
  
  <li class="has-submenu">
                      <a href="#"> <i class="ti-user"></i>Trainers</a>
                      <ul class="submenu">
                          <li><a href="{% url 'trainers:trainer_create' %}">Add New Trainer</a></li>
                          <li><a href="{% url 'trainers:trainer_view' %}">View All Trainers</a></li>

                      </ul>
                  </li>

                  <li>
                      <a href="#">Student Registration History</a>
                  </li>
              </ul>
              <!-- End navigation menu -->
              <div class="clearfix"></div>
          </div>
          <!-- end #navigation -->
          <div class="clearfix"></div>
      </div>
  </div>
  <!-- end Topbar -->
</header>